name: Website Bug Report
description: Report an issue with the Power Platform ToolBox website.
title: "[Bug]: "
labels: ["bug", "triage"]
type: "bug"
projects: ["PowerPlatformToolBox/1"]
body:
    - type: markdown
      attributes:
          value: |
              Thanks for taking the time to file a website bug.

              > [!NOTE]
                > **If this is a documentation issue**, please report it in the [pptb-docs-web repository](https://github.com/PowerPlatformToolBox/pptb-docs-web/issues) instead.

    - type: dropdown
      id: issue-category
      attributes:
          label: Issue category
          description: Select the type of issue you're reporting.
          options:
              - General website bug
              - Tool submission problem
              - Tool listing or search issue
              - Performance or loading issue
              - Other
          default: 0
      validations:
          required: true

    - type: input
      id: page-url
      attributes:
          label: Page URL
          description: Provide the exact URL where the issue occurs.
          placeholder: https://powerplatformtoolbox.com/tools/...
      validations:
          required: true

    - type: textarea
      id: what-happened
      attributes:
          label: What happened?
          description: Describe the issue and what you expected to happen instead.
          placeholder: Tell us what you see and what you expected.
      validations:
          required: true

    - type: textarea
      id: repro-steps
      attributes:
          label: Steps to reproduce
          description: List clear steps so we can reproduce the issue.
          placeholder: |
              1. Go to ...
              2. Click ...
              3. Observe ...
      validations:
          required: true

    - type: input
      id: browser
      attributes:
          label: Browser and version
          description: "Example: Edge 130.0.2849.80, Chrome 131.0.6778.86, Safari 17.5."
          placeholder: Browser name and version
      validations:
          required: false

    - type: input
      id: os
      attributes:
          label: Operating system and device
          description: "Example: Windows 11 (desktop), macOS 15 (MacBook), iOS 26 (iPhone), Android 14 (Pixel 8)."
          placeholder: OS and device
      validations:
          required: false

    - type: textarea
      id: console-logs
      attributes:
          label: Console errors (if any)
          description: Copy-paste any relevant console errors.
          render: shell

    - type: textarea
      id: screenshots
      attributes:
          label: Screenshots or screen recording
          description: Drag and drop images or a short video if helpful.

    - type: textarea
      id: additional-info
      attributes:
          label: Additional context
          description: Anything else we should know (feature flags, ad blockers, VPN, etc.).



